// <auto-generated />
using System;
using DataAccessLayer.Concrete;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EntityLayer.Concrete.About", b =>
                {
                    b.Property<int>("About_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("About_Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("About_Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("About_MapLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("About_Status")
                        .HasColumnType("bit");

                    b.HasKey("About_ID");

                    b.ToTable("Abouts");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Belenco", b =>
                {
                    b.Property<int>("Belenco_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Belenco_Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Belenco_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Belenco_Status")
                        .HasColumnType("bit");

                    b.HasKey("Belenco_ID");

                    b.ToTable("Belencos");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Calisco", b =>
                {
                    b.Property<int>("Calisco_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Calisco_Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Calisco_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Calisco_Status")
                        .HasColumnType("bit");

                    b.HasKey("Calisco_ID");

                    b.ToTable("Caliscos");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Cimstone", b =>
                {
                    b.Property<int>("Cimstone_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cimstone_Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cimstone_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Cimstone_Status")
                        .HasColumnType("bit");

                    b.HasKey("Cimstone_ID");

                    b.ToTable("Cimstones");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Coante", b =>
                {
                    b.Property<int>("Coante_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Coante_Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Coante_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Coante_Status")
                        .HasColumnType("bit");

                    b.HasKey("Coante_ID");

                    b.ToTable("Coantes");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Contact", b =>
                {
                    b.Property<int>("Contact_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Contact_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Contact_Mail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contact_Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Contact_Status")
                        .HasColumnType("bit");

                    b.Property<string>("Contact_Subject")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contact_UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Contact_ID");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Granit", b =>
                {
                    b.Property<int>("Granit_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Granit_Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Granit_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Granit_Status")
                        .HasColumnType("bit");

                    b.HasKey("Granit_ID");

                    b.ToTable("Granits");
                });
#pragma warning restore 612, 618
        }
    }
}
